# Generated by Django 3.0.8 on 2020-08-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cost_apply_form',
            field=models.CharField(choices=[('...', 'Choose'), ('fue', 'Functional English'), ('acw', 'Accademic Writting'), ('aps', 'Applied Spoken English'), ('ei', 'EILTS'), ('tf', 'TOEFL'), ('sat', 'SAT'), ('be', 'Bussines English'), ('bj', 'broadcast Journalism'), ('ems', 'English for Medical Student'), ('egs', 'English for Engineering Student'), ('eb', 'English for Bankers'), ('pm', 'Print Media'), ('ve', 'Video Editing'), ('bcs', 'Basic Computer Skills'), ('w', 'Webdesign'), ('p', 'Programming'), ('c', 'Criminology'), ('mg', 'Management and Goverment'), ('dph', 'Deploma Public Health'), ('phc', 'Public Health Certificate'), ('ctg', 'Cinematography')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(blank=True, max_length=56),
        ),
    ]
